[server]
headless = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0d6efd"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans serif"
